
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: npm run build
      - run: npm run test

      - persist_to_workspace:
          root: ~/repo
          paths:
            - build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run: sudo pip install awscli
      - run: aws s3 sync build/ s3://${bucket} --region ${region} --delete
      - run: aws cloudfront create-invalidation --distribution-id ${distribution} --paths *

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
